apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  type: Nodeport
  selector:
    app: go
  ports:
  - targetport: 8080
    port: 8080
    protocol: TCP
    nodeport: 30008
    